# Generated by Django 5.1.3 on 2024-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_req', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('Leak', 'Gas Leak'), ('Installation', 'New Installation'), ('Maintenance', 'Maintenance'), ('Billing', 'Billing Inquiry'), ('Other', 'Other')], max_length=50),
        ),
    ]
