# Generated by Django 5.1.3 on 2024-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_req', '0002_alter_servicerequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/'),
        ),
    ]
